title: Ibukun Olorire Oparinu
logo: Ibukun.Jpeg.jpg
description: A data analyst with experience using advance microsoft excel, SQL and PowerBi for providing business intelligent report.
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
